### ISSUE TITLE
`MasterTranslation.text_for_language_code` should use the translation cache

### ISSUE THREAD

**Issue by martinallison** [potatolondon/fluent-2.0#24]
Currently it looks up the translation object, skipping the cache, every time.

``` python
def text_for_language_code(self, lang_code):
    new_code = find_closest_supported_language(lang_code)
    if new_code not in self.translations_by_language_code.keys():
        # we don't have a translation for this language
        return self.text

    translation_id = self.translations_by_language_code[new_code]
    translation = Translation.objects.get(id=translation_id)

    return translation.text
```

**Comment by grzes** [comment]
Thanks @martinallison this just came up ... again and I'm fixing it. We'll also attempt to cache the master translations, so instead of doing 2 db queries per translated field access we'll be doing 0. 

Also: on Django >= 1.8 it's possible for get_language() to return None, so we'll add the behaviour of displaying the master.text when translations are deactivated.
